### ISSUE TITLE
Validation query error : 390100 (08004): Incorrect username or password was specified.

### ISSUE THREAD

**Issue by reshdesu** [michelin/snowflake-grafana-datasource#75]
Even after specifying correct id and password the package fails to connect to snowflake.
Things that I can share,
1. Our snowflake admins were able to look at their logs and noted a rejection for wrong password on their end.
![5-16-2024 3-47-45 PM](https://github.com/michelin/snowflake-grafana-datasource/assets/12244870/b2830a8e-c528-44b1-b6f8-0fd832a28665)
2. Using snowflake UI allows me to log in with the account.
3. We tried with 2 accounts, one with some special characters in password and other with a very simple alphanumeric password

**Comment by devnied** [comment]
I can't reproduce your problem.

- Which version of Grafana and plugin do you use?
- Do you have any other errors in Grafana logs?

**Comment by nalberto** [comment]
Same issue on my side

**Comment by a2intl** [comment]
This is an issue when the password contains a `+` (plus sign), because [getConnectionString](https://github.com/michelin/snowflake-grafana-datasource/blob/1d5d684a/pkg/snowflake.go#L114) uses `url.UserPassword` (which does not URL-escape `+`) while the `gosnowflake` library uses `url.QueryUnescape` in [ParseDSN](https://github.com/snowflakedb/gosnowflake/blob/27e76c9349a38895e20a847b4c08d01d39ec4d03/dsn.go#L402), which does unescape the `+` to a space character . @devnied , I can submit a patch for this (which I've verified as working) if you'd like to reopen this issue.
